### ISSUE TITLE
iterative ref: expand_1d_to_3d

### ISSUE THREAD

**Issue by geoffwoollard** [compSPI/reconstructSPI#20]
TODO: arr_1d fsc_1d to 3d (spherical shells)

**Comment by geoffwoollard** [comment]
One simple way to do this in general is to have the one_d array and then just multiply through reshaping on the three axes.

`three_d = one_d.reshape(-1,1,1) * one_d.reshape(1,-1,1) * one_d.reshape(1,1,-1)`

**Comment by thisFreya** [comment]
@geoffwoollard can I get some clarification on this? What I am thinking is that the 1D array *arr* (n // 2 indices *i*) will correspond to spherical shells of radius *i* that have values *arr[i]* across the entire shell. Is this correct?

**Comment by geoffwoollard** [comment]
> One simple way to do this in general is to have the one_d array and then just multiply through reshaping on the three axes.
> 
> `three_d = one_d.reshape(-1,1,1) * one_d.reshape(1,-1,1) * one_d.reshape(1,1,-1)`

Actually, I'm not 100% sure this works...

**Comment by geoffwoollard** [comment]
@thisTyler 

> @geoffwoollard can I get some clarification on this? What I am thinking is that the 1D array _arr_ (n // 2 indices _i_) will correspond to spherical shells of radius _i_ that have values _arr[i]_ across the entire shell. Is this correct?

Yes, that's the idea. The 1D array is the ray going from the edge of the sphere (which is in a box). 

So these are necessary conditions

```
assert np.allclose(arr_1d[:], arr_3d[n//2:,n//2,n//2])
assert np.allclose(arr_1d[:], arr_3d[n//2,n//2:,n//2])
assert np.allclose(arr_1d[:], arr_3d[n//2,n//2,n//2:])
```

**Comment by thisFreya** [comment]
There is one more subtlety here - the final array has n_pix (EVEN) dimensions. So, is it preferable to have a sphere of the form:
```
- - 1 1 - -    - - - - - -
- 1 1 1 1 -    - - 1 - - -
1 1 1 1 1 1    - 1 1 1 - -
1 1 1 1 1 1 or 1 1 1 1 1 -
- 1 1 1 1 -    - 1 1 1 - -
- - 1 1 - -    - - 1 - - -
```
(Ignoring the diamond-shaped limitations of my demonstration medium) should the spheres have "copied" max radii sections that are 2 rows wide?

For now, I am going with the former (2-wide) as it removes ambiguity about which edges of the domain get used.

**Comment by geoffwoollard** [comment]
The Fourier shell correlation is in a shell (just a particular frequency band), not a sphere (which includes all the inside).

Each pixel has a coordinate. Note that the origin (0,0), in real/primal space, is not centered, because there is no central pixel but two halves, with the first one in the right/second half being the origin / DC component. 

The coordinates along a central line are [-n//2, -n//2+1, ..., -2, -1, 0,1,2,...,n//2-1]. The left half is [-n//2, -n//2+1, ..., -2, -1] and the right half is [0,1,2,...,n//2-1].

Each pixel has an (x,y) coordinate and you can take the hypotenuse to get the radius. This gives a number for every pixel. You can threshold on this and make a mask. There are all sorts of heuristics here. To just keep one pixel wide. To have a gentle windowing function (e.g. Gaussian).

That's real/primal space. But we are making shells in Fourier/frequency space.

You first need to figure out the coordinates in the 1D array, and on the 2D array. See screenshot.

Just do the simplest things now and keep the "shell function" modular. I write the above for reference.

<img width="667" alt="Screen Shot 2022-03-29 at 8 37 41 AM" src="https://user-images.githubusercontent.com/4852692/160651157-4d823780-0b61-4b6a-93dd-42765a35de77.png">


That screenshot comes from p. 15 of https://github.com/geoffwoollard/learn_cryoem_math/blob/master/cryoem-group-study-meeting/meeting.pdf


Penczek, P. A. (2020). Reliable cryo-EM resolution estimation with modified Fourier shell correlation. IUCrJ, 7(6), 1–14. http://doi.org/10.1107/s2052252520011574

**Comment by geoffwoollard** [comment]
That screenshot comes from p. 15 of https://github.com/geoffwoollard/learn_cryoem_math/blob/master/cryoem-group-study-meeting/meeting.pdf
